export const enum CalendarEventType {
  SOWING_NURSERY = 'SOWING_NURSERY',
  SOWING_DIRECT = 'SOWING_DIRECT',
  BED_PREPARATION = 'BED_PREPARATION',
  TRANSPLATATION = 'TRANSPLATATION',
  HARVEST = 'HARVEST'
}
