export class ErrorKeys {
  static INVALID_ID = 'errors.INVALID_ID';
  static INVALID_FORM = 'errors.INVALID_FORM';
  static UNEXPECTED_ERROR = 'errors.UNEXPECTED_ERROR';
  static FAILED_TO_CREATE_ADMIN_ACCOUNT = 'errors.FAILED_TO_CREATE_ADMIN_ACCOUNT';
  static ACOOUNT_NEEDS_ACTIVATION = 'errors.ACOOUNT_NEEDS_ACTIVATION';
  static INVALID_CREDENTIALS = 'errors.INVALID_CREDENTIALS';
}
