export class MessageKeys {
  static ERROR_TITLE = 'ERROR_TITLE';
  static SAVED_TITLE = 'SAVED_TITLE';
  static EMAIL_VERIFIED_TITLE = 'EMAIL_VERIFIED_TITLE';
  static YOU_MAY_NOW_LOGIN = 'YOU_MAY_NOW_LOGIN';
  static ADMIN_ACCOUNT_CREATED_TITLE = 'ADMIN_ACCOUNT_CREATED_TITLE';
  static LOGIN_FAILED_TITLE = 'LOGIN_FAILED_TITLE';
  static EMAIL_SENT_TITLE = 'EMAIL_SENT_TITLE';
  static CHECK_MAIL_FOR_PASSWORD_RESET_MESSAGE = 'CHECK_MAIL_FOR_PASSWORD_RESET_MESSAGE';
  static EMAIL_COULD_NOT_BE_SENT_TITLE = 'EMAIL_COULD_NOT_BE_SENT_TITLE';
  static PASSWORD_RESET_SUCCESS_TITLE = 'PASSWORD_RESET_SUCCESS_TITLE';
  static PASSWORD_RESET_SUCCESS_MESSAGE = 'PASSWORD_RESET_SUCCESS_MESSAGE';
  static PASSWORD_RESET_ERROR_TITLE = 'PASSWORD_RESET_ERROR_TITLE';
  static ACCOUNT_CREATED_TITLE = 'ACCOUNT_CREATED_TITLE';
  static ACCOUNT_REGISTRATION_ERROR_TITLE = 'ACCOUNT_REGISTRATION_ERROR_TITLE';
  static SESSION_EXPIRED_TITLE = 'SESSION_EXPIRED_TITLE';
  static SIGN_IN_AGAIN_MESSAGE = 'SIGN_IN_AGAIN_MESSAGE';
  static ERROR_UPDATING_CULTURE_TITLE = 'ERROR_UPDATING_CULTURE_TITLE';
  static MOON_ZODIAC_HIDDEN_MESSAGE = 'MOON_ZODIAC_HIDDEN_MESSAGE';
  static MOON_ZODIAC_HIDDEN_DETAILS = 'MOON_ZODIAC_HIDDEN_DETAILS';

  static NAME_LABEL = 'NAME_LABEL';
  static SPECIES_LABEL = 'SPECIES_LABEL';
  static CULTIVAR_LABEL = 'CULTIVAR_LABEL';
  static PRODUCT_LABEL = 'PRODUCT_LABEL';
  static CROP_PLANT_LABEL = 'CROP_PLANT_LABEL';
  static CROP_PRODUCT_LABEL = 'CROP_PRODUCT_LABEL';
  static BED_LABEL = 'BED_LABEL';
  static SOWING_DATE_LABEL = 'SOWING_DATE_LABEL';
  static GERMINATION_DATE_LABEL = 'GERMINATION_DATE_LABEL';
  static FIRST_HARVEST_LABEL = 'FIRST_HARVEST_LABEL';
  static LAST_HARVEST_LABEL = 'LAST_HARVEST_LABEL';
  static BED_OCCUPANCY_START_DATE_LABEL = 'BED_OCCUPANCY_START_DATE_LABEL';
  static HTML_NOTES_LABEL = 'HTML_NOTES_LABEL';
  static NURSERING_DURATION_LABEL = 'NURSERING_DURATION_LABEL';
  static NURSERING_START_DATE_LABEL = 'NURSERING_START_DATE_LABEL';
  static CULTURE_PREPARATION_DURATION_LABEL = 'CULTURE_PREPARATION_DURATION_LABEL';
  static CULTURE_PREPARATION_START_DATE_LABEL = 'CULTURE_PREPARATION_START_DATE_LABEL';

  static MOON_PHASE_TITLE = 'MOON_PHASE_TITLE';
  static MOON_ZODIAC_TITLE = 'MOON_ZODIAC_TITLE';
  static NURSERY_TITLE = 'NURSERY_TITLE';


  static ENUM_CULTURE_PHASE_MESSAGE_KEYS = {
    _PREFIX: 'CULTURE_PHASE_TYPE.',
    PREPARATION_PRESOWING: 'CULTURE_PHASE_TYPE.PREPARATION_PRESOWING',
    PREPARATION_COVER: 'CULTURE_PHASE_TYPE.PREPARATION_COVER',
    GERMINATION: 'CULTURE_PHASE_TYPE.GERMINATION',
    NURSING: 'CULTURE_PHASE_TYPE.NURSING',
    GROWTH: 'CULTURE_PHASE_TYPE.GROWTH',
    HARVEST: 'CULTURE_PHASE_TYPE.HARVEST',
  };
  static ENUM_ZODIAC_ELEMENTS_MESSAGE_KEYS = {
    _PREFIX: 'ZODIAC_ELEMENT.',
    FIRE: 'ZODIAC_ELEMENT.FIRE',
    EARTH: 'ZODIAC_ELEMENT.EARTH',
    WIND: 'ZODIAC_ELEMENT.WIND',
    WATER: 'ZODIAC_ELEMENT.WATER',
  };
  static ENUM_MOON_PHASES_KEYS = {
    _PREFIX: 'MOON_PHASE.',
    NEW_MOON: 'MOON_PHASE.NEW',
    FIRST_QUARTER: 'MOON_PHASE.FIRST_QUARTER',
    FULL_MOON: 'MOON_PHASE.FULL',
    THIRD_QUARTER: 'MOON_PHASE.THIRD_QUARTER',
  };
  static ENUM_ZODIAC_NAMES__KEYS = {
    _PREFIX: 'ZODIAC.',
    ARIES: 'ZODIAC.ARIES',
    TAURUS: 'ZODIAC.TAURUS',
    GEMINI: 'ZODIAC.GEMINI',
    CANCER: 'ZODIAC.CANCER',
    LEO: 'ZODIAC.LEO',
    VIRGO: 'ZODIAC.VIRGO',
    LIBRA: 'ZODIAC.LIBRA',
    SCORPIO: 'ZODIAC.SCORPIO',
    SAGITTARIUS: 'ZODIAC.SAGITTARIUS',
    CAPRICORN: 'ZODIAC.CAPRICORN',
    AQUARIUS: 'ZODIAC.AQUARIUS',
    PISCES: 'ZODIAC.PISCES',
  };
  static ENUM_CULTURE_STEPS_NAMES__KEYS = {
    _PREFIX: 'CULTURE_STEP.',
    CULTURE: 'CULTURE_STEP.CULTURE',
    DATES: 'CULTURE_STEP.DATES',
    QUANTITITES: 'CULTURE_STEP.QUANTITITES',
    PREPARATION: 'CULTURE_STEP.PREPARATION',
  };
  static PARAMETRIZED_MESSAGE_KEYS = {
    MOON_ZODIAC_TITLE: 'PARAMETRIZED.MOON_ZODIAC_TITLE',
    MOON_PHASE_TITLE: 'PARAMETRIZED.MOON_PHASE_TITLE',
    CULTURE_PHASE_TITLE: 'PARAMETRIZED.CULTURE_PHASE_TITLE',
  };
}
